import 'package:flutter/foundation.dart' show debugPrint;

/// Oyun genelinde kullanılan lokalize string haritası ve yardımcı araçlar.
class AppStrings {
  AppStrings._();

  static const String storeTitle = "Racing Hub: Idle Tycoon";

  // ─── Otantik Yarış Atı İsimleri Havuzu ───
  static const List<String> raceHorsePool = [
    'Thunderbolt', 'Silver Arrow', 'Desert Storm', 'Night Fury',
    'Golden Flash', 'Iron Duke', 'Crimson Tide', 'Wild Wind',
    'Black Diamond', 'Royal Flush', 'Storm Chase', 'Wild Card',
    'Lucky Strike', 'Blazing Star', 'Celtic Fire', 'Midnight Run',
    'Falcon Ridge', 'Shadow Dance', 'Prairie Wind', 'Steel Force',
    'Arctic Blast', 'Fire Dragon', 'Ocean Wave', 'Canyon King',
    'Phantom Ride', 'Eagle Eye', 'Copper Crown', 'Amber Flame',
    'Blue Bolt', 'Ruby Quest', 'Jade Spirit', 'Silk Road',
    'River Bend', 'Mountain Peak', 'Sunrise Glory', 'Stardust',
    'Noble Quest', 'Titan Force', 'Silver Ghost', 'Rapid Flash',
    'Thunder King', 'Windy Blaze', 'Storm Rider', 'Desert Wind',
    'Brave Heart', 'Swift Arrow', 'Iron Will', 'Golden Dream',
  ];

  // ─── Kompakt Sayı Formatlayıcı ───
  /// 1234 → 1.2K | 1234567 → 1.23M | 1234 → 1234
  static String formatGold(double n) {
    if (n >= 1000000000) {
      final b = n / 1000000000;
      return '${b.toStringAsFixed(b >= 10 ? 1 : 2)}B';
    }
    if (n >= 1000000) {
      final m = n / 1000000;
      return '${m.toStringAsFixed(m >= 10 ? 1 : 2)}M';
    }
    if (n >= 1000) {
      final k = n / 1000;
      return '${k.toStringAsFixed(k >= 100 ? 0 : 1)}K';
    }
    return n.toStringAsFixed(0);
  }

  static const Map<String, Map<String, String>> _strings = {
    // ══════════════════════════════════════
    // TÜRKÇE
    // ══════════════════════════════════════
    'tr': {
      // Sekmeler
      'tab_derby': 'Yarış',
      'tab_stable': 'Ahır',
      'tab_jockeys': 'Jokeyler',
      'tab_facilities': 'Tesis',
      'tab_market': 'Market',

      // HUD
      'boost_active': '2X Aktif',
      'boost_get': '2X Boost Al',
      'passive_per_sec': '/sn',
      'lang_toggle': '🇬🇧 EN',

      // Yarış Alanı
      'win_chance': 'kazanma',
      'rank_prefix': 'Anlık:',
      'form_label': 'Form:',
      'gate_prefix': 'K',
      'next_race_label': 'Sonraki:',
      'you_label': 'SEN',

      // Derby Sekmesi
      'live_commentary': 'Canlı Anlatım',
      'active_team': 'Aktif Takım',
      'season_standings': '🏆 Sezon Sıralaması',
      'your_score_prefix': 'Sen:',
      'race_count_suffix': 'yarış tamamlandı',
      'points_info': '1. → 30p | 2. → 15p | 3. → 5p',
      'you_row': '🏇 Sen',
      'rival_prefix': '🐎',

      // Lig Dialog
      'league_dialog_title': '🏟️ Lig Seçimi',
      'league_active': '✓ Aktif',
      'close': 'Kapat',

      // Ahır
      'train_btn': 'Antren',
      'locked_horse_title': 'Bu At Kilitli!',
      'locked_horse_desc': 'ligine geç ve kilidi aç.',
      'cards_label': 'Kartlar:',
      'edit_name_title': '✏️ At İsmini Düzenle',
      'edit_name_hint': 'Yeni isim gir...',
      'free_rename_notice': '✏️ İlk değişiklik ücretsiz!',
      'ad_rename_notice': '📺 İsim değiştirmek için reklam gerekli',
      'save_btn': 'Kaydet',
      'cancel_btn': 'İptal',
      'watch_ad_btn': '📺 Reklam İzle',
      'rename_success': '✅ İsim güncellendi!',
      'horse_name_label': 'At İsmi:',

      // Jokey
      'locked_jockey_title': 'Bu Jokey Kilitli!',
      'locked_jockey_desc': 'ligine geç ve kilidi aç.',

      // Tesis
      'yield_label': 'Kazanç:',
      'upgrade_btn': 'Yükselt',

      // Market
      'league_chests_title': 'Lig Kasaları',
      'card_merge_title': 'Kart Birleştirme (5\'e 1)',
      'gear_slots_title': 'Aktif Ekipman Slotları',
      'equip_bag_title': 'Ekipman Çantası',
      'equip_bag_empty': 'Ekipman çantanız boş.',
      'premium_title': 'Premium Geliştirmeler',
      'total_label': 'Toplam:',
      'merge_btn': 'Birleştir',
      'locked_chest': 'Kilitli',
      'equip_btn': 'Tak',
      'unequip_label': 'ÇIKAR',
      'equipped_label': 'TAKILI',

      // Genel
      'not_enough_gold': '🪙 Yeterli altın yok!',
      'not_enough_diamonds': '💎 Yeterli elmas yok!',
      'excellent_btn': 'Harika!',
      'continue_btn': 'Devam Et!',
      'awesome_btn': 'Mükemmel!',
      'great_btn': 'Süper!',
      'no_btn': 'Hayır',

      // Gacha
      'card_drawn_title': '🎉 KART ÇEKİLDİ! 🎉',
      'horse_type': 'At',
      'jockey_type': 'Jokey',
      'tier_label': 'Tier',
      'card_dup_note': 'Yinelenen kart ahırına eklendi!\n5 kart topla ve birleştir!',

      // Merge
      'merge_success_title': '✨ BİRLEŞTİRME BAŞARILI! ✨',
      'stars_upgraded': 'Yıldıza Yükseltildi!',

      // Terfi
      'promotion_title': '🏆 LİG YÜKSELTME! 🏆',
      'promoted_to': 'Tebrikler! Yeni liga terfi ettin:',
      'promotion_note': 'Altın kazancı 10x arttı! Yeni pistlerde başarı şansın sıfırlandı.',

      // Sezon Sonu
      'season_champion_title': '🏆 SEZON ŞAMPİYONU!',
      'season_ended_title': '🏁 Sezon Bitti',
      'new_season_btn': 'Yeni Sezon Başlat!',
      'your_points': 'Senin Puanın:',
      'current_class': 'Mevcut Sınıf:',
      'class_promoted_note': '🎉 Birinci oldun! Sınıf yükseltildi!',

      // Sponsor
      'sponsor_title': '🎌 Sponsor Ödülü!',
      'sponsor_msg': 'Sponsor bayraktarına tıkladın!\nÜcretsiz altın kazanmak için devam et.',
      'play_earn_btn': 'Oyna & Kazan',
      'sponsor_claimed': '🎌 Sponsor altını kazanıldı!',

      // Çevrimdışı
      'welcome_back_title': '🐎 Tekrar Hoş Geldin!',
      'offline_earned_label': 'Yokluğunda ahırında birikti:',
      'offline_cap_note': 'Maks. 2 saatlik çevrimdışı kazanç hesaplandı.',
      'collect_btn': 'Topla',
      'double_ad_btn': '2X Reklam İzle',
      'doubled_msg': '⚡ Kazancın iki katına çıktı!',

      // Premium
      'insta_win_title': 'Anında Kazanma Bileti',
      'insta_win_desc': 'Anlık 1. sırayı garantile!',
      'insta_win_success': '⚡ Anında Kazandın! 1. Sıra!',
      'gold_diamond_trade': 'Altın → Elmas',
      'trade_btn': 'Değiştir',

      // Canlı Anlatım
      'commentary_ready': '🏁 Hipodrom hazır! Yarış yakında başlıyor...',
      'commentary_gates_open': '🏁 Kapılar açıldı! Yarış başlıyor!',
      'commentary_leading': '⚡ ÖNDESIN! Tempoyu koru!',
      'commentary_rival_leads': 'öne geçti!',
      'commentary_finished_1st': '🏆 KAZANDIN! 1. oldun!',
      'commentary_finished_top': 'bitirdin! Harika iş!',
      'commentary_finished_low': 'bitirdin. Daha sert antren et!',

      // Ayarlar & Sıralama & Reklam
      'settings_title': 'Ayarlar',
      'settings_lang_label': 'Dil:',
      'settings_close': 'Kapat',
      'settings_sound': 'Ses Efektleri:',
      'settings_music': 'Müzik:',
      'settings_vibrate': 'Titreşim:',
      'settings_on': 'Açık',
      'settings_off': 'Kapalı',
      'promote_btn': 'Terfi Et',
      'restart_free_btn': 'Sezonu Sıfırla (Ücretsiz)',
      'promote_desc': 'Yeni Seviye / Lige terfi et.',
      'restart_desc': 'Terfi etmeden sezonu yeniden başlat.',
      'col_rank': 'Sıra',
      'col_jockey': 'Jokey',
      'col_horse': 'At',
      'col_points': 'Puan',
      'ad_playing': 'Reklam oynatılıyor... Kalan süre:',
      'ad_completed': 'Reklam tamamlandı!',
      'season_end_gold_cost': 'Ücret:',
      'not_enough_gold_promote': 'Terfi etmek için yeterli altın yok!',
      // Geliştirme İsimleri ve Açıklamaları
      'stat_speed_name': 'Hız',
      'stat_speed_desc': 'Maksimum Hız',
      'stat_acceleration_name': 'İvme',
      'stat_acceleration_desc': 'Patlama Hızı',
      'stat_stamina_name': 'Dayanıklılık',
      'stat_stamina_desc': 'Uzun Koşu',
      'stat_focus_name': 'Odak',
      'stat_focus_desc': 'Jokey Uyumu',
      'stat_temper_name': 'Sakinlik',
      'stat_temper_desc': 'Baskı Altında',
      'stat_cornering_name': 'Dönüş',
      'stat_cornering_desc': 'Viraj Hakimiyeti',
      'skill_tactics_name': 'Taktik',
      'skill_tactics_desc': 'Stratejik kararlar',
      'skill_pacing_name': 'Tempo',
      'skill_pacing_desc': 'Hız yönetimi',
      'skill_reflexes_name': 'Refleksler',
      'skill_reflexes_desc': 'Anlık tepkiler',
      'building_training_track_name': 'Otopark',
      'building_training_track_desc': 'Ziyaretçiler için park alanı',
      'building_medical_center_name': 'Antrenman Pisti',
      'building_medical_center_desc': 'Sürekli antrenman devreleri',
      'building_feed_storage_name': 'Sağlık Merkezi',
      'building_feed_storage_desc': 'Rehabilitasyon & takviye',
      'building_research_lab_name': 'Ahır',
      'building_research_lab_desc': 'Atlar için barınak',
      'building_luxury_stable_name': 'Lüks Ahır',
      'building_luxury_stable_desc': 'Birinci sınıf yaşam alanı',
      'promotion_success': '🏆 Başarıyla terfi ettin!',
      'chest_error_gold': 'Yeterli altın yok veya kasa kilitli!',
      'chest_error_diamond': 'Yeterli elmas yok veya kasa kilitli!',
      'merge_error': 'Birleştirmek için 5 yinelenen kart gerekli!',
    },

    // ══════════════════════════════════════
    // ENGLISH
    // ══════════════════════════════════════
    'en': {
      // Tabs
      'tab_derby': 'Derby',
      'tab_stable': 'Stable',
      'tab_jockeys': 'Jockeys',
      'tab_facilities': 'Facilities',
      'tab_market': 'Market',

      // HUD
      'boost_active': '2X Active',
      'boost_get': 'Get 2X Boost',
      'passive_per_sec': '/sec',
      'lang_toggle': '🇹🇷 TR',

      // Race Area
      'win_chance': 'win chance',
      'rank_prefix': 'Current:',
      'form_label': 'Form:',
      'gate_prefix': 'G',
      'next_race_label': 'Next:',
      'you_label': 'YOU',

      // Derby Tab
      'live_commentary': 'Live Commentary',
      'active_team': 'Active Team',
      'season_standings': '🏆 Season Standings',
      'your_score_prefix': 'Yours:',
      'race_count_suffix': 'races done',
      'points_info': '1st → 30p | 2nd → 15p | 3rd → 5p',
      'you_row': '🏇 You',
      'rival_prefix': '🐎',

      // League Dialog
      'league_dialog_title': '🏟️ League Selection',
      'league_active': '✓ Active',
      'close': 'Close',

      // Stable
      'train_btn': 'Train',
      'locked_horse_title': 'This Horse is Locked!',
      'locked_horse_desc': 'Promote to unlock.',
      'cards_label': 'Cards:',
      'edit_name_title': '✏️ Edit Horse Name',
      'edit_name_hint': 'Enter new name...',
      'free_rename_notice': '✏️ First rename is free!',
      'ad_rename_notice': '📺 An ad is required to rename',
      'save_btn': 'Save',
      'cancel_btn': 'Cancel',
      'watch_ad_btn': '📺 Watch Ad',
      'rename_success': '✅ Name updated!',
      'horse_name_label': 'Horse Name:',

      // Jockey
      'locked_jockey_title': 'This Jockey is Locked!',
      'locked_jockey_desc': 'Promote to unlock.',

      // Facilities
      'yield_label': 'Yield:',
      'upgrade_btn': 'Upgrade',

      // Market
      'league_chests_title': 'League Chests',
      'card_merge_title': 'Card Merge Station (5-to-1)',
      'gear_slots_title': 'Active Gear Slots',
      'equip_bag_title': 'Equipment Bag',
      'equip_bag_empty': 'Your equipment bag is empty.',
      'premium_title': 'Premium Enhancements',
      'total_label': 'Total:',
      'merge_btn': 'Merge',
      'locked_chest': 'Locked',
      'equip_btn': 'Equip',
      'unequip_label': 'UNEQUIP',
      'equipped_label': 'EQUIPPED',

      // General
      'not_enough_gold': '🪙 Not enough Gold!',
      'not_enough_diamonds': '💎 Not enough Diamonds!',
      'excellent_btn': 'Excellent!',
      'continue_btn': 'Continue!',
      'awesome_btn': 'Awesome!',
      'great_btn': 'Great!',
      'no_btn': 'No',

      // Gacha
      'card_drawn_title': '🎉 CARD DRAWN! 🎉',
      'horse_type': 'Horse',
      'jockey_type': 'Jockey',
      'tier_label': 'Tier',
      'card_dup_note': 'Duplicate card added to your stable!\nCollect 5 to merge and upgrade stars!',

      // Merge
      'merge_success_title': '✨ MERGE SUCCESSFUL! ✨',
      'stars_upgraded': 'Stars Upgraded!',

      // Promotion
      'promotion_title': '🏆 LEAGUE PROMOTION! 🏆',
      'promoted_to': 'Outstanding! You promoted to:',
      'promotion_note': 'Gold yield scaled 10x! Win difficulty reset for new tracks.',

      // Season End
      'season_champion_title': '🏆 SEASON CHAMPION!',
      'season_ended_title': '🏁 Season Ended',
      'new_season_btn': 'Start New Season!',
      'your_points': 'Your Points:',
      'current_class': 'Current Class:',
      'class_promoted_note': '🎉 You finished 1st! Class promoted!',

      // Sponsor
      'sponsor_title': '🎉 Sponsor Reward!',
      'sponsor_msg': 'You tapped the sponsor flag!\nContinue to earn free gold.',
      'play_earn_btn': 'Watch & Earn',
      'sponsor_claimed': '🎌 Sponsor gold claimed!',

      // Offline
      'welcome_back_title': '🐎 Welcome Back!',
      'offline_earned_label': 'Your stables earned while you were away:',
      'offline_cap_note': 'Max 2-hour offline earnings calculated.',
      'collect_btn': 'Collect',
      'double_ad_btn': 'Watch Ad for 2X',
      'doubled_msg': '⚡ Your earnings were doubled!',

      // Premium
      'insta_win_title': 'Insta-Win Ticket',
      'insta_win_desc': 'Instantly guarantee 1st place!',
      'insta_win_success': '⚡ You won instantly! 1st Place!',
      'gold_diamond_trade': 'Gold → Diamond',
      'trade_btn': 'Trade',

      // Live Commentary
      'commentary_ready': '🏁 Hipodrome ready! Race starting soon...',
      'commentary_gates_open': '🏁 Gates open! Race is on!',
      'commentary_leading': '⚡ YOU ARE LEADING! Keep it up!',
      'commentary_rival_leads': 'is leading!',
      'commentary_finished_1st': '🏆 YOU WON! Finished 1st!',
      'commentary_finished_top': 'finish! Great work!',
      'commentary_finished_low': 'finish. Train harder!',

      // Settings & Standings & Ad
      'settings_title': 'Settings',
      'settings_lang_label': 'Language:',
      'settings_close': 'Close',
      'settings_sound': 'Sound Effects:',
      'settings_music': 'Music:',
      'settings_vibrate': 'Vibration:',
      'settings_on': 'On',
      'settings_off': 'Off',
      'promote_btn': 'Promote',
      'restart_free_btn': 'Restart Season (Free)',
      'promote_desc': 'Promote to the next Class / League.',
      'restart_desc': 'Restart the season without promotion.',
      'col_rank': 'Rank',
      'col_jockey': 'Jockey',
      'col_horse': 'Horse',
      'col_points': 'Points',
      'ad_playing': 'Ad playing... Time remaining:',
      'ad_completed': 'Ad completed!',
      'season_end_gold_cost': 'Fee:',
      'not_enough_gold_promote': 'Not enough gold to promote!',
      // Upgrade Names and Descriptions
      'stat_speed_name': 'Speed',
      'stat_speed_desc': 'Maximum Speed',
      'stat_acceleration_name': 'Acceleration',
      'stat_acceleration_desc': 'Burst Speed',
      'stat_stamina_name': 'Stamina',
      'stat_stamina_desc': 'Long Run',
      'stat_focus_name': 'Focus',
      'stat_focus_desc': 'Jockey Synergy',
      'stat_temper_name': 'Temper',
      'stat_temper_desc': 'Under Pressure',
      'stat_cornering_name': 'Cornering',
      'stat_cornering_desc': 'Cornering Control',
      'skill_tactics_name': 'Tactics',
      'skill_tactics_desc': 'Strategic decisions',
      'skill_pacing_name': 'Pacing',
      'skill_pacing_desc': 'Speed management',
      'skill_reflexes_name': 'Reflexes',
      'skill_reflexes_desc': 'Instant reactions',
      'building_training_track_name': 'Parking Lot',
      'building_training_track_desc': 'Parking area for visitors',
      'building_medical_center_name': 'Training Track',
      'building_medical_center_desc': 'Continuous training circuits',
      'building_feed_storage_name': 'Health Center',
      'building_feed_storage_desc': 'Rehabilitation & therapy',
      'building_research_lab_name': 'Stall',
      'building_research_lab_desc': 'Shelter for horses',
      'building_luxury_stable_name': 'Luxury Stable',
      'building_luxury_stable_desc': 'Premium living space',
      'promotion_success': '🏆 Successfully promoted!',
      'chest_error_gold': 'Not enough gold or chest is locked!',
      'chest_error_diamond': 'Not enough diamonds or chest is locked!',
      'merge_error': '5 duplicate cards required to merge!',
    },

    // ══════════════════════════════════════
    // SPANISH
    // ══════════════════════════════════════
    'es': {
      'tab_derby': 'Derbi',
      'tab_stable': 'Establo',
      'tab_jockeys': 'Jockeys',
      'tab_facilities': 'Instalaciones',
      'tab_market': 'Mercado',
      'boost_active': '2X Activo',
      'boost_get': 'Obtener 2X Boost',
      'passive_per_sec': '/seg',
      'lang_toggle': '🇪🇸 ES',
      'win_chance': 'ganar',
      'rank_prefix': 'Actual:',
      'form_label': 'Forma:',
      'gate_prefix': 'C',
      'next_race_label': 'Siguiente:',
      'you_label': 'TÚ',
      'live_commentary': 'Comentarios en Vivo',
      'active_team': 'Equipo Activo',
      'season_standings': '🏆 Clasificación de Temporada',
      'your_score_prefix': 'Tú:',
      'race_count_suffix': 'carreras terminadas',
      'points_info': '1º → 30p | 2º → 15p | 3º → 5p',
      'you_row': '🏇 Tú',
      'rival_prefix': '🐎',
      'league_dialog_title': '🏟️ Selección de Liga',
      'league_active': '✓ Activo',
      'close': 'Cerrar',
      'train_btn': 'Entrenar',
      'locked_horse_title': '¡Este caballo está bloqueado!',
      'locked_horse_desc': 'Pasa a la liga para desbloquear.',
      'cards_label': 'Cartas:',
      'edit_name_title': '✏️ Editar Nombre del Caballo',
      'edit_name_hint': 'Nuevo nombre...',
      'free_rename_notice': '✏️ ¡Primer cambio gratis!',
      'ad_rename_notice': '📺 Se requiere anuncio para cambiar nombre',
      'save_btn': 'Guardar',
      'cancel_btn': 'Cancelar',
      'watch_ad_btn': '📺 Ver Anuncio',
      'rename_success': '✅ ¡Nombre actualizado!',
      'horse_name_label': 'Nombre del Caballo:',
      'locked_jockey_title': '¡Este jockey está bloqueado!',
      'locked_jockey_desc': 'Pasa a la liga para desbloquear.',
      'yield_label': 'Rendimiento:',
      'upgrade_btn': 'Mejorar',
      'league_chests_title': 'Cofres de Liga',
      'card_merge_title': 'Fusión de Cartas (5 a 1)',
      'gear_slots_title': 'Ranuras de Equipo Activo',
      'equip_bag_title': 'Bolsa de Equipo',
      'equip_bag_empty': 'Tu bolsa de equipo está vacía.',
      'premium_title': 'Mejoras Premium',
      'total_label': 'Total:',
      'merge_btn': 'Fusionar',
      'locked_chest': 'Bloqueado',
      'equip_btn': 'Equipar',
      'unequip_label': 'DESEQUIPAR',
      'equipped_label': 'EQUIPADO',
      'not_enough_gold': '🪙 ¡No hay suficiente oro!',
      'not_enough_diamonds': '💎 ¡No hay suficientes diamantes!',
      'excellent_btn': '¡Excelente!',
      'continue_btn': '¡Continuar!',
      'awesome_btn': '¡Increíble!',
      'great_btn': '¡Súper!',
      'no_btn': 'No',
      'card_drawn_title': '🎉 ¡CARTA EXTRAÍDA! 🎉',
      'horse_type': 'Caballo',
      'jockey_type': 'Jockey',
      'tier_label': 'Nivel',
      'card_dup_note': '¡Carta duplicada añadida al establo!\n¡Reúne 5 para fusionar y mejorar estrellas!',
      'merge_success_title': '✨ ¡FUSIÓN EXITOSA! ✨',
      'stars_upgraded': '¡Estrellas mejoradas!',
      'promotion_title': '🏆 ¡ASCENSO DE LIGA! 🏆',
      'promoted_to': '¡Felicidades! Ascendiste a:',
      'promotion_note': '¡Ingresos de oro multiplicados por 10! Dificultad restablecida.',
      'season_champion_title': '🏆 ¡CAMPEÓN DE LA TEMPORADA!',
      'season_ended_title': '🏁 Fin de Temporada',
      'new_season_btn': '¡Iniciar Nueva Temporada!',
      'your_points': 'Tus Puntos:',
      'current_class': 'Clase Actual:',
      'class_promoted_note': '🎉 ¡Terminaste 1º! ¡Clase ascendida!',
      'sponsor_title': '🎌 ¡Recompensa de Patrocinador!',
      'sponsor_msg': '¡Tocaste al patrocinador!\nContinúa para ganar oro gratis.',
      'play_earn_btn': 'Ver y Ganar',
      'sponsor_claimed': '🎌 ¡Oro del patrocinador reclamado!',
      'welcome_back_title': '🐎 ¡Bienvenido de nuevo!',
      'offline_earned_label': 'Tu establo acumuló en tu ausencia:',
      'offline_cap_note': 'Cálculo para un máx. de 2 horas çevrimdışı.',
      'collect_btn': 'Recoger',
      'double_ad_btn': 'Ver Anuncio para 2X',
      'doubled_msg': '⚡ ¡Tus ingresos se duplicaron!',
      'insta_win_title': 'Boleto de Victoria Instantánea',
      'insta_win_desc': '¡Garantiza el 1er lugar al instante!',
      'insta_win_success': '⚡ ¡Ganaste al instante! ¡1er Lugar!',
      'gold_diamond_trade': 'Oro → Diamante',
      'trade_btn': 'Cambiar',
      'commentary_ready': '🏁 ¡Hipódromo listo! La carrera comenzará pronto...',
      'commentary_gates_open': '🏁 ¡Puertas abiertas! ¡Comienza la carrera!',
      'commentary_leading': '⚡ ¡ESTÁS LIDERANDO! ¡Mantén el ritmo!',
      'commentary_rival_leads': '¡tomó la delantera!',
      'commentary_finished_1st': '🏆 ¡GANASTE! ¡Quedaste 1º!',
      'commentary_finished_top': '¡terminaste! ¡Gran trabajo!',
      'commentary_finished_low': 'terminaste. ¡Entrena más duro!',
      'settings_title': 'Configuración',
      'settings_lang_label': 'Idioma:',
      'settings_close': 'Cerrar',
      'settings_sound': 'Efectos de Sonido:',
      'settings_music': 'Música:',
      'settings_vibrate': 'Vibración:',
      'settings_on': 'Encendido',
      'settings_off': 'Apagado',
      'promote_btn': 'Ascender',
      'restart_free_btn': 'Reiniciar Temporada (Gratis)',
      'promote_desc': 'Ascender a la siguiente clase/liga.',
      'restart_desc': 'Reiniciar la temporada sin ascender.',
      'col_rank': 'Posición',
      'col_jockey': 'Jockey',
      'col_horse': 'Caballo',
      'col_points': 'Puntos',
      'ad_playing': 'Anuncio reproduciéndose... Resta:',
      'ad_completed': '¡Anuncio completado!',
      'season_end_gold_cost': 'Costo:',
      'not_enough_gold_promote': '¡No hay suficiente oro para ascender!',
      'stat_speed_name': 'Velocidad',
      'stat_speed_desc': 'Velocidad Máxima',
      'stat_acceleration_name': 'Aceleración',
      'stat_acceleration_desc': 'Velocidad de Arranque',
      'stat_stamina_name': 'Resistencia',
      'stat_stamina_desc': 'Carrera Larga',
      'stat_focus_name': 'Enfoque',
      'stat_focus_desc': 'Sinergia de Jockey',
      'stat_temper_name': 'Templanza',
      'stat_temper_desc': 'Bajo Presión',
      'stat_cornering_name': 'Giro',
      'stat_cornering_desc': 'Control de Giros',
      'skill_tactics_name': 'Táctica',
      'skill_tactics_desc': 'Decisiones estratégicas',
      'skill_pacing_name': 'Ritmo',
      'skill_pacing_desc': 'Control de velocidad',
      'skill_reflexes_name': 'Reflejos',
      'skill_reflexes_desc': 'Reacciones instantáneas',
      'building_training_track_name': 'Estacionamiento',
      'building_training_track_desc': 'Área de estacionamiento de visitantes',
      'building_medical_center_name': 'Pista de Entrenamiento',
      'building_medical_center_desc': 'Circuitos continuos de entrenamiento',
      'building_feed_storage_name': 'Centro Médico',
      'building_feed_storage_desc': 'Rehabilitación y terapia',
      'building_research_lab_name': 'Pesebrera',
      'building_research_lab_desc': 'Refugio para caballos',
      'building_luxury_stable_name': 'Establo de Lujo',
      'building_luxury_stable_desc': 'Espacio habitable premium',
      'promotion_success': '🏆 ¡Ascendido con éxito!',
      'chest_error_gold': '¡Oro insuficiente o cofre bloqueado!',
      'chest_error_diamond': '¡Diamantes insuficientes o cofre bloqueado!',
      'merge_error': '¡Se necesitan 5 cartas duplicadas para fusionar!',
    },

    // ══════════════════════════════════════
    // PORTUGUESE (BRAZIL)
    // ══════════════════════════════════════
    'pt': {
      'tab_derby': 'Derbi',
      'tab_stable': 'Estábulo',
      'tab_jockeys': 'Jóqueis',
      'tab_facilities': 'Instalações',
      'tab_market': 'Mercado',
      'boost_active': '2X Ativo',
      'boost_get': 'Obter 2X Boost',
      'passive_per_sec': '/seg',
      'lang_toggle': '🇧🇷 PT',
      'win_chance': 'vencer',
      'rank_prefix': 'Atual:',
      'form_label': 'Forma:',
      'gate_prefix': 'P',
      'next_race_label': 'Próxima:',
      'you_label': 'VOCÊ',
      'live_commentary': 'Comentários ao Vivo',
      'active_team': 'Equipe Ativa',
      'season_standings': '🏆 Classificação da Temporada',
      'your_score_prefix': 'Você:',
      'race_count_suffix': 'corridas concluídas',
      'points_info': '1º → 30p | 2º → 15p | 3º → 5p',
      'you_row': '🏇 Você',
      'rival_prefix': '🐎',
      'league_dialog_title': '🏟️ Seleção de Liga',
      'league_active': '✓ Ativo',
      'close': 'Fechar',
      'train_btn': 'Treinar',
      'locked_horse_title': 'Este cavalo está bloqueado!',
      'locked_horse_desc': 'Passe para a liga para desbloquear.',
      'cards_label': 'Cartas:',
      'edit_name_title': '✏️ Editar Nome do Cavalo',
      'edit_name_hint': 'Novo nome...',
      'free_rename_notice': '✏️ Primeira alteração grátis!',
      'ad_rename_notice': '📺 Um anúncio é necessário para renomear',
      'save_btn': 'Salvar',
      'cancel_btn': 'Cancelar',
      'watch_ad_btn': '📺 Assistir Anúncio',
      'rename_success': '✅ Nome atualizado!',
      'horse_name_label': 'Nome do Cavalo:',
      'locked_jockey_title': 'Este jóquei está bloqueado!',
      'locked_jockey_desc': 'Passe para a liga para desbloquear.',
      'yield_label': 'Rendimento:',
      'upgrade_btn': 'Melhorar',
      'league_chests_title': 'Baús de Liga',
      'card_merge_title': 'Fusão de Cartas (5 para 1)',
      'gear_slots_title': 'Slots de Equipamento Ativo',
      'equip_bag_title': 'Bolsa de Equipamento',
      'equip_bag_empty': 'Sua bolsa de equipamento está vazia.',
      'premium_title': 'Melhorias Premium',
      'total_label': 'Total:',
      'merge_btn': 'Mesclar',
      'locked_chest': 'Bloqueado',
      'equip_btn': 'Equipar',
      'unequip_label': 'REMOVER',
      'equipped_label': 'EQUIPADO',
      'not_enough_gold': '🪙 Ouro insuficiente!',
      'not_enough_diamonds': '💎 Diamantes insuficientes!',
      'excellent_btn': 'Excelente!',
      'continue_btn': 'Continuar!',
      'awesome_btn': 'Incrível!',
      'great_btn': 'Super!',
      'no_btn': 'Não',
      'card_drawn_title': '🎉 CARTA EXTRAÍDA! 🎉',
      'horse_type': 'Cavalo',
      'jockey_type': 'Jóquei',
      'tier_label': 'Nível',
      'card_dup_note': 'Carta duplicada adicionada ao estábulo!\nReúna 5 para mesclar e subir estrelas!',
      'merge_success_title': '✨ FUSÃO BEM-SUCEDIDA! ✨',
      'stars_upgraded': 'Estrelas atualizadas!',
      'promotion_title': '🏆 PROMOÇÃO DE LIGA! 🏆',
      'promoted_to': 'Parabéns! Você foi promovido para:',
      'promotion_note': 'Rendimento de ouro multiplicado por 10! Dificuldade resetada.',
      'season_champion_title': '🏆 CAMPEÃO DA TEMPORADA!',
      'season_ended_title': '🏁 Fim da Temporada',
      'new_season_btn': 'Iniciar Nova Temporada!',
      'your_points': 'Seus Pontos:',
      'current_class': 'Classe Atual:',
      'class_promoted_note': '🎉 Você terminou em 1º! Classe promovida!',
      'sponsor_title': '🎌 Recompensa do Patrocinador!',
      'sponsor_msg': 'Você tocou no patrocinador!\nContinue para ganhar ouro grátis.',
      'play_earn_btn': 'Assistir e Ganhar',
      'sponsor_claimed': '🎌 Ouro do patrocinador resgatado!',
      'welcome_back_title': '🐎 Bem-vindo de volta!',
      'offline_earned_label': 'Seu estábulo acumulou na sua ausência:',
      'offline_cap_note': 'Cálculo para no máx. 2 horas offline.',
      'collect_btn': 'Coletar',
      'double_ad_btn': 'Assistir Anúncio para 2X',
      'doubled_msg': '⚡ Seus ganhos foram duplicados!',
      'insta_win_title': 'Bilhete de Vitória Instantânea',
      'insta_win_desc': 'Garanta o 1º lugar instantaneamente!',
      'insta_win_success': '⚡ Você venceu instantaneamente! 1º Lugar!',
      'gold_diamond_trade': 'Ouro → Diamante',
      'trade_btn': 'Trocar',
      'commentary_ready': '🏁 Hipódromo pronto! A corrida começará em breve...',
      'commentary_gates_open': '🏁 Portões abertos! A corrida começou!',
      'commentary_leading': '⚡ VOCÊ ESTÁ LIDERANDO! Mantenha o ritmo!',
      'commentary_rival_leads': 'assumiu a liderança!',
      'commentary_finished_1st': '🏆 VOCÊ VENCEU! Terminou em 1º!',
      'commentary_finished_top': 'terminou! Ótimo trabalho!',
      'commentary_finished_low': 'terminou. Treine mais duro!',
      'settings_title': 'Configurações',
      'settings_lang_label': 'Idioma:',
      'settings_close': 'Fechar',
      'settings_sound': 'Efeitos de Som:',
      'settings_music': 'Música:',
      'settings_vibrate': 'Vibração:',
      'settings_on': 'Ligado',
      'settings_off': 'Desligado',
      'promote_btn': 'Promover',
      'restart_free_btn': 'Reiniciar Temporada (Grátis)',
      'promote_desc': 'Promover para a próxima classe/liga.',
      'restart_desc': 'Reiniciar a temporada sem promover.',
      'col_rank': 'Posição',
      'col_jockey': 'Jóquei',
      'col_horse': 'Cavalo',
      'col_points': 'Pontos',
      'ad_playing': 'Anúncio rodando... Tempo restante:',
      'ad_completed': 'Anúncio concluído!',
      'season_end_gold_cost': 'Custo:',
      'not_enough_gold_promote': 'Sem ouro suficiente para promover!',
      'stat_speed_name': 'Velocidade',
      'stat_speed_desc': 'Velocidade Máxima',
      'stat_acceleration_name': 'Aceleración',
      'stat_acceleration_desc': 'Velocidade de Explosão',
      'stat_stamina_name': 'Resistência',
      'stat_stamina_desc': 'Corrida Longa',
      'stat_focus_name': 'Foco',
      'stat_focus_desc': 'Sinergia do Jóquei',
      'stat_temper_name': 'Temperamento',
      'stat_temper_desc': 'Sob Pressão',
      'stat_cornering_name': 'Curva',
      'stat_cornering_desc': 'Controle de Curva',
      'skill_tactics_name': 'Tática',
      'skill_tactics_desc': 'Decisões estratégicas',
      'skill_pacing_name': 'Ritmo',
      'skill_pacing_desc': 'Gestão de velocidade',
      'skill_reflexes_name': 'Reflexos',
      'skill_reflexes_desc': 'Reações instantâneas',
      'building_training_track_name': 'Estacionamento',
      'building_training_track_desc': 'Área de estacionamento para visitantes',
      'building_medical_center_name': 'Pista de Treino',
      'building_medical_center_desc': 'Circuitos contínuos de treino',
      'building_feed_storage_name': 'Centro Médico',
      'building_feed_storage_desc': 'Reabilitação e terapia',
      'building_research_lab_name': 'Baia',
      'building_research_lab_desc': 'Abrigo para os cavalos',
      'building_luxury_stable_name': 'Estábulo de Luxo',
      'building_luxury_stable_desc': 'Espaço de vida premium',
      'promotion_success': '🏆 Promovido com sucesso!',
      'chest_error_gold': 'Sem ouro suficiente ou baú bloqueado!',
      'chest_error_diamond': 'Sem diamantes suficientes ou baú bloqueado!',
      'merge_error': 'São necessárias 5 cartas duplicadas para mesclar!',
    },

    // ══════════════════════════════════════
    // GERMAN
    // ══════════════════════════════════════
    'de': {
      'tab_derby': 'Derby',
      'tab_stable': 'Stall',
      'tab_jockeys': 'Jockeys',
      'tab_facilities': 'Anlagen',
      'tab_market': 'Markt',
      'boost_active': '2X Aktiv',
      'boost_get': 'Hol 2X Boost',
      'passive_per_sec': '/Sek',
      'lang_toggle': '🇩🇪 DE',
      'win_chance': 'Sieg',
      'rank_prefix': 'Aktuell:',
      'form_label': 'Form:',
      'gate_prefix': 'B',
      'next_race_label': 'Nächstes:',
      'you_label': 'DU',
      'live_commentary': 'Live-Kommentar',
      'active_team': 'Aktives Team',
      'season_standings': '🏆 Saison-Rangliste',
      'your_score_prefix': 'Du:',
      'race_count_suffix': 'Rennen abgeschlossen',
      'points_info': '1. → 30p | 2. → 15p | 3. → 5p',
      'you_row': '🏇 Du',
      'rival_prefix': '🐎',
      'league_dialog_title': '🏟️ Ligaauswahl',
      'league_active': '✓ Aktiv',
      'close': 'Schließen',
      'train_btn': 'Trainieren',
      'locked_horse_title': 'Dieses Pferd ist gesperrt!',
      'locked_horse_desc': 'Wechsle in die Liga, um es freizuschalten.',
      'cards_label': 'Karten:',
      'edit_name_title': '✏️ Pferdenamen bearbeiten',
      'edit_name_hint': 'Neuer Name...',
      'free_rename_notice': '✏️ Erste Umbenennung kostenlos!',
      'ad_rename_notice': '📺 Anzeige erforderlich für Namensänderung',
      'save_btn': 'Speichern',
      'cancel_btn': 'Abbrechen',
      'watch_ad_btn': '📺 Werbung ansehen',
      'rename_success': '✅ Name aktualisiert!',
      'horse_name_label': 'Pferdename:',
      'locked_jockey_title': 'Dieser Jockey ist gesperrt!',
      'locked_jockey_desc': 'Wechsle in die Liga, um ihn freizuschalten.',
      'yield_label': 'Ertrag:',
      'upgrade_btn': 'Aufwerten',
      'league_chests_title': 'Liga-Truhen',
      'card_merge_title': 'Kartenfusion (5 zu 1)',
      'gear_slots_title': 'Aktive Ausrüstungsslots',
      'equip_bag_title': 'Ausrüstungstasche',
      'equip_bag_empty': 'Deine Ausrüstungstasche ist leer.',
      'premium_title': 'Premium-Upgrades',
      'total_label': 'Gesamt:',
      'merge_btn': 'Fusionieren',
      'locked_chest': 'Gesperrt',
      'equip_btn': 'Ausrüsten',
      'unequip_label': 'ABLEGEN',
      'equipped_label': 'AUSGERÜSTET',
      'not_enough_gold': '🪙 Nicht genug Gold!',
      'not_enough_diamonds': '💎 Nicht genug Diamanten!',
      'excellent_btn': 'Exzellent!',
      'continue_btn': 'Weiter!',
      'awesome_btn': 'Großartig!',
      'great_btn': 'Super!',
      'no_btn': 'Nein',
      'card_drawn_title': '🎉 KARTE GEZOGEN! 🎉',
      'horse_type': 'Pferd',
      'jockey_type': 'Jockey',
      'tier_label': 'Rang',
      'card_dup_note': 'Duplikatkarte dem Stall hinzugefügt!\nSammle 5, um sie zu fusionieren!',
      'merge_success_title': '✨ FUSION ERFOLGREICH! ✨',
      'stars_upgraded': 'Sterne aufgewertet!',
      'promotion_title': '🏆 LIGA-AUFSTIEG! 🏆',
      'promoted_to': 'Herzlichen Glückwunsch! Aufgestiegen zu:',
      'promotion_note': 'Goldertrag verzehnfacht! Schwierigkeitsgrad zurückgesetzt.',
      'season_champion_title': '🏆 SAISON-CHAMPION!',
      'season_ended_title': '🏁 Saison beendet',
      'new_season_btn': 'Neue Saison starten!',
      'your_points': 'Deine Punkte:',
      'current_class': 'Aktuelle Klasse:',
      'class_promoted_note': '🎉 Du hast als 1. beendet! Klasse befördert!',
      'sponsor_title': '🎌 Sponsorenbelohnung!',
      'sponsor_msg': 'Du hast den Sponsor angetippt!\nWeiter, um kostenloses Gold zu erhalten.',
      'play_earn_btn': 'Ansehen & Verdienen',
      'sponsor_claimed': '🎌 Sponsorgold erhalten!',
      'welcome_back_title': '🐎 Willkommen zurück!',
      'offline_earned_label': 'Dein Stall hat in deiner Abwesenheit verdient:',
      'offline_cap_note': 'Berechnet für max. 2 Stunden offline.',
      'collect_btn': 'Sammeln',
      'double_ad_btn': 'Werbung ansehen für 2X',
      'doubled_msg': '⚡ Dein Verdienst wurde verdoppelt!',
      'insta_win_title': 'Sofort-Sieg-Ticket',
      'insta_win_desc': 'Garantiere sofort den 1. Platz!',
      'insta_win_success': '⚡ Sofort gewonnen! 1. Platz!',
      'gold_diamond_trade': 'Gold → Diamanten',
      'trade_btn': 'Tauschen',
      'commentary_ready': '🏁 Rennbahn bereit! Das Rennen beginnt bald...',
      'commentary_gates_open': '🏁 Startboxen geöffnet! Das Rennen läuft!',
      'commentary_leading': '⚡ DU FÜHRST! Halt das Tempo!',
      'commentary_rival_leads': 'hat die Führung übernommen!',
      'commentary_finished_1st': '🏆 GEWONNEN! Du bist 1. geworden!',
      'commentary_finished_top': 'beendet! Tolle Arbeit!',
      'commentary_finished_low': 'beendet. Trainiere härter!',
      'settings_title': 'Einstellungen',
      'settings_lang_label': 'Sprache:',
      'settings_close': 'Schließen',
      'settings_sound': 'Soundeffekte:',
      'settings_music': 'Musik:',
      'settings_vibrate': 'Vibration:',
      'settings_on': 'An',
      'settings_off': 'Aus',
      'promote_btn': 'Befördern',
      'restart_free_btn': 'Saison zurücksetzen (Kostenlos)',
      'promote_desc': 'In die nächste Klasse / Liga aufsteigen.',
      'restart_desc': 'Saison ohne Beförderung neu starten.',
      'col_rank': 'Rang',
      'col_jockey': 'Jockey',
      'col_horse': 'Pferd',
      'col_points': 'Punkte',
      'ad_playing': 'Werbung läuft... Verbleibend:',
      'ad_completed': 'Werbung beendet!',
      'season_end_gold_cost': 'Gebühr:',
      'not_enough_gold_promote': 'Nicht genug Gold für Beförderung!',
      // Upgrade Names and Descriptions
      'stat_speed_name': 'Tempo',
      'stat_speed_desc': 'Höchstgeschwindigkeit',
      'stat_acceleration_name': 'Beschleunigung',
      'stat_acceleration_desc': 'Antrittsgeschwindigkeit',
      'stat_stamina_name': 'Ausdauer',
      'stat_stamina_desc': 'Langstreckenlauf',
      'stat_focus_name': 'Fokus',
      'stat_focus_desc': 'Jockey-Synergie',
      'stat_temper_name': 'Gelassenheit',
      'stat_temper_desc': 'Unter Druck',
      'stat_cornering_name': 'Kurvenfahrt',
      'stat_cornering_desc': 'Kurvenkontrolle',
      'skill_tactics_name': 'Taktik',
      'skill_tactics_desc': 'Strategische Entscheidungen',
      'skill_pacing_name': 'Pacing',
      'skill_pacing_desc': 'Geschwindigkeitsmanagement',
      'skill_reflexes_name': 'Reflexe',
      'skill_reflexes_desc': 'Sofortige Reaktionen',
      'building_training_track_name': 'Parkplatz',
      'building_training_track_desc': 'Parkplatz für Besucher',
      'building_medical_center_name': 'Trainingsbahn',
      'building_medical_center_desc': 'Kontinuierliche Trainingsrunden',
      'building_feed_storage_name': 'Medizinisches Zentrum',
      'building_feed_storage_desc': 'Rehabilitation & Therapie',
      'building_research_lab_name': 'Stallbox',
      'building_research_lab_desc': 'Unterkunft für Pferde',
      'building_luxury_stable_name': 'Luxusstall',
      'building_luxury_stable_desc': 'Erstklassiger Wohnraum',
      'promotion_success': '🏆 Erfolgreich befördert!',
      'chest_error_gold': 'Nicht genug Gold oder Truhe gesperrt!',
      'chest_error_diamond': 'Nicht genug Diamanten oder Truhe gesperrt!',
      'merge_error': '5 Duplikatkarten zum Fusionieren erforderlich!',
    },

    // ══════════════════════════════════════
    // FRENCH
    // ══════════════════════════════════════
    'fr': {
      'tab_derby': 'Derby',
      'tab_stable': 'Écurie',
      'tab_jockeys': 'Jockeys',
      'tab_facilities': 'Infrastructures',
      'tab_market': 'Marché',
      'boost_active': '2X Actif',
      'boost_get': 'Obtenir Boost 2X',
      'passive_per_sec': '/sec',
      'lang_toggle': '🇫🇷 FR',
      'win_chance': 'victoire',
      'rank_prefix': 'Actuel:',
      'form_label': 'Forme:',
      'gate_prefix': 'P',
      'next_race_label': 'Suivant:',
      'you_label': 'VOUS',
      'live_commentary': 'Commentaires en Direct',
      'active_team': 'Équipe Active',
      'season_standings': '🏆 Classement de la Saison',
      'your_score_prefix': 'Vous:',
      'race_count_suffix': 'courses terminées',
      'points_info': '1er → 30p | 2e → 15p | 3e → 5p',
      'you_row': '🏇 Vous',
      'rival_prefix': '🐎',
      'league_dialog_title': '🏟️ Sélection de Ligue',
      'league_active': '✓ Actif',
      'close': 'Fermer',
      'train_btn': 'Entraîner',
      'locked_horse_title': 'Ce cheval est verrouillé !',
      'locked_horse_desc': 'Passez à la ligue pour le déverrouiller.',
      'cards_label': 'Cartes :',
      'edit_name_title': '✏️ Modifier le Nom du Cheval',
      'edit_name_hint': 'Nouveau nom...',
      'free_rename_notice': '✏️ Premier changement gratuit !',
      'ad_rename_notice': '📺 Une publicité est requise pour renommer',
      'save_btn': 'Sauvegarder',
      'cancel_btn': 'Annuler',
      'watch_ad_btn': '📺 Regarder la Publicité',
      'rename_success': '✅ Nom mis à jour !',
      'horse_name_label': 'Nom du Cheval :',
      'locked_jockey_title': 'Ce jockey est verrouillé !',
      'locked_jockey_desc': 'Passez à la ligue pour le déverrouiller.',
      'yield_label': 'Rendement :',
      'upgrade_btn': 'Améliorer',
      'league_chests_title': 'Coffres de Ligue',
      'card_merge_title': 'Fusion de Cartes (5 pour 1)',
      'gear_slots_title': 'Slots d\'Équipement Actifs',
      'equip_bag_title': 'Sac d\'Équipement',
      'equip_bag_empty': 'Votre sac d\'équipement est vide.',
      'premium_title': 'Améliorations Premium',
      'total_label': 'Total :',
      'merge_btn': 'Fusionner',
      'locked_chest': 'Verrouillé',
      'equip_btn': 'Équiper',
      'unequip_label': 'RETIRER',
      'equipped_label': 'ÉQUIPÉ',
      'not_enough_gold': '🪙 Pas assez d\'or !',
      'not_enough_diamonds': '💎 Pas assez de diamants !',
      'excellent_btn': 'Excellent !',
      'continue_btn': 'Continuer !',
      'awesome_btn': 'Superbe !',
      'great_btn': 'Super !',
      'no_btn': 'Non',
      'card_drawn_title': '🎉 CARTE TIRÉE ! 🎉',
      'horse_type': 'Cheval',
      'jockey_type': 'Jockey',
      'tier_label': 'Niveau',
      'card_dup_note': 'Carte en double ajoutée à l\'écurie !\nRéunissez-en 5 pour fusionner et améliorer les étoiles !',
      'merge_success_title': '✨ FUSION RÉUSSIE ! ✨',
      'stars_upgraded': 'Étoiles améliorées !',
      'promotion_title': '🏆 PROMOTION DE LIGUE ! 🏆',
      'promoted_to': 'Félicitations ! Vous êtes promu en :',
      'promotion_note': 'Rendement d\'or multiplié par 10 ! Difficulté réinitialisée.',
      'season_champion_title': '🏆 CHAMPION DE LA SAISON !',
      'season_ended_title': '🏁 Fin de Saison',
      'new_season_btn': 'Lancer une Nouvelle Saison !',
      'your_points': 'Vos Points :',
      'current_class': 'Classe Actuelle :',
      'class_promoted_note': '🎉 Vous avez fini 1er ! Classe promue !',
      'sponsor_title': '🎌 Récompense du Sponsor !',
      'sponsor_msg': 'Vous avez appuyé sur le sponsor !\nContinuez pour gagner de l\'or gratuit.',
      'play_earn_btn': 'Regarder & Gagner',
      'sponsor_claimed': '🎌 Or du sponsor récupéré !',
      'welcome_back_title': '🐎 Bon Retour !',
      'offline_earned_label': 'Votre écurie a accumulé en votre absence :',
      'offline_cap_note': 'Calculé pour un maximum de 2 heures hors ligne.',
      'collect_btn': 'Récupérer',
      'double_ad_btn': 'Regarder une Publicité pour 2X',
      'doubled_msg': '⚡ Vos gains ont été doublés !',
      'insta_win_title': 'Ticket Victoire Instantanée',
      'insta_win_desc': 'Garantissez instantanément la 1ère place !',
      'insta_win_success': '⚡ Gagné instantanément ! 1ère Place !',
      'gold_diamond_trade': 'Or → Diamant',
      'trade_btn': 'Échanger',
      'commentary_ready': '🏁 Hippodrome prêt ! La course commence bientôt...',
      'commentary_gates_open': '🏁 Portes ouvertes ! La course est lancée !',
      'commentary_leading': '⚡ VOUS MENEZ ! Gardez le rythme !',
      'commentary_rival_leads': 'a pris la tête !',
      'commentary_finished_1st': '🏆 VOUS AVEZ GAGNÉ ! Fini 1er !',
      'commentary_finished_top': 'fini ! Beau travail !',
      'commentary_finished_low': 'fini. Entraînez-vous plus dur !',
      'settings_title': 'Paramètres',
      'settings_lang_label': 'Langue :',
      'settings_close': 'Fermer',
      'settings_sound': 'Effets Sonores :',
      'settings_music': 'Musique :',
      'settings_vibrate': 'Vibration :',
      'settings_on': 'Actif',
      'settings_off': 'Désactivé',
      'promote_btn': 'Promouvoir',
      'restart_free_btn': 'Réinitialiser la Saison (Gratuit)',
      'promote_desc': 'Promouvoir à la classe / ligue suivante.',
      'restart_desc': 'Recommencer la saison sans promotion.',
      'col_rank': 'Rang',
      'col_jockey': 'Jockey',
      'col_horse': 'Cheval',
      'col_points': 'Points',
      'ad_playing': 'Publicité en cours... Reste :',
      'ad_completed': 'Publicité terminée !',
      'season_end_gold_cost': 'Frais :',
      'not_enough_gold_promote': 'Pas assez d\'or pour promouvoir !',
      // Upgrade Names and Descriptions
      'stat_speed_name': 'Vitesse',
      'stat_speed_desc': 'Vitesse Maximale',
      'stat_acceleration_name': 'Accélération',
      'stat_acceleration_desc': 'Vitesse de Pointe',
      'stat_stamina_name': 'Endurance',
      'stat_stamina_desc': 'Course Longue',
      'stat_focus_name': 'Concentration',
      'stat_focus_desc': 'Synergie avec le Jockey',
      'stat_temper_name': 'Tempérament',
      'stat_temper_desc': 'Sous Pression',
      'stat_cornering_name': 'Virage',
      'stat_cornering_desc': 'Contrôle des Virages',
      'skill_tactics_name': 'Tactique',
      'skill_tactics_desc': 'Décisions stratégiques',
      'skill_pacing_name': 'Allure',
      'skill_pacing_desc': 'Gestion de la vitesse',
      'skill_reflexes_name': 'Réflexes',
      'skill_reflexes_desc': 'Réactions instantanées',
      'building_training_track_name': 'Parking',
      'building_training_track_desc': 'Aire de stationnement des visiteurs',
      'building_medical_center_name': 'Piste d\'Entraînement',
      'building_medical_center_desc': 'Circuits d\'entraînement continus',
      'building_feed_storage_name': 'Centre Médical',
      'building_feed_storage_desc': 'Réhabilitation & thérapie',
      'building_research_lab_name': 'Stalle',
      'building_research_lab_desc': 'Abri pour les chevaux',
      'building_luxury_stable_name': 'Écurie de Luxe',
      'building_luxury_stable_desc': 'Espace de vie haut de gamme',
      'promotion_success': '🏆 Promu avec succès !',
      'chest_error_gold': 'Or insuffisant ou coffre verrouillé !',
      'chest_error_diamond': 'Diamants insuffisants ou coffre verrouillé !',
      'merge_error': '5 cartes en double requises pour fusionner !',
    },

    // ══════════════════════════════════════
    // RUSSIAN
    // ══════════════════════════════════════
    'ru': {
      'tab_derby': 'Дерби',
      'tab_stable': 'Стойло',
      'tab_jockeys': 'Жокеи',
      'tab_facilities': 'Объекты',
      'tab_market': 'Магазин',
      'boost_active': '2X Активно',
      'boost_get': 'Получить 2X Буст',
      'passive_per_sec': '/сек',
      'lang_toggle': '🇷🇺 RU',
      'win_chance': 'победа',
      'rank_prefix': 'Тек:',
      'form_label': 'Форма:',
      'gate_prefix': 'В',
      'next_race_label': 'След:',
      'you_label': 'ВЫ',
      'live_commentary': 'Прямая трансляция',
      'active_team': 'Активная команда',
      'season_standings': '🏆 Таблица сезона',
      'your_score_prefix': 'Вы:',
      'race_count_suffix': 'гонок завершено',
      'points_info': '1-й → 30о | 2-й → 15о | 3-й → 5о',
      'you_row': '🏇 Вы',
      'rival_prefix': '🐎',
      'league_dialog_title': '🏟️ Выбор лиги',
      'league_active': '✓ Активно',
      'close': 'Закрыть',
      'train_btn': 'Тренировка',
      'locked_horse_title': 'Эта лошадь заблокирована!',
      'locked_horse_desc': 'Перейдите в лигу для разблокировки.',
      'cards_label': 'Карты:',
      'edit_name_title': '✏️ Изменить имя лошади',
      'edit_name_hint': 'Введите новое имя...',
      'free_rename_notice': '✏️ Первое изменение бесплатно!',
      'ad_rename_notice': '📺 Требуется реклама для переименования',
      'save_btn': 'Сохранить',
      'cancel_btn': 'Отмена',
      'watch_ad_btn': '📺 Смотреть рекламу',
      'rename_success': '✅ Имя обновлено!',
      'horse_name_label': 'Имя лошади:',
      'locked_jockey_title': 'Этот жокей заблокирован!',
      'locked_jockey_desc': 'Перейдите в лигу для разблокировки.',
      'yield_label': 'Доход:',
      'upgrade_btn': 'Улучшить',
      'league_chests_title': 'Сундуки лиги',
      'card_merge_title': 'Слияние карт (5 к 1)',
      'gear_slots_title': 'Активные слоты снаряжения',
      'equip_bag_title': 'Сумка снаряжения',
      'equip_bag_empty': 'Сумка снаряжения пуста.',
      'premium_title': 'Премиум улучшения',
      'total_label': 'Всего:',
      'merge_btn': 'Слияние',
      'locked_chest': 'Закрыто',
      'equip_btn': 'Надеть',
      'unequip_label': 'СНЯТЬ',
      'equipped_label': 'НАДЕТО',
      'not_enough_gold': '🪙 Недостаточно золота!',
      'not_enough_diamonds': '💎 Недостаточно алмазов!',
      'excellent_btn': 'Отлично!',
      'continue_btn': 'Продолжить!',
      'awesome_btn': 'Потрясающе!',
      'great_btn': 'Супер!',
      'no_btn': 'Нет',
      'card_drawn_title': '🎉 КАРТА ВЫТЯНУТА! 🎉',
      'horse_type': 'Лошадь',
      'jockey_type': 'Жокей',
      'tier_label': 'Ранг',
      'card_dup_note': 'Дубликат карты добавлен в стойло!\nСоберите 5 для слияния и повышения звезд!',
      'merge_success_title': '✨ СЛИЯНИЕ УСПЕШНО! ✨',
      'stars_upgraded': 'Звезды улучшены!',
      'promotion_title': '🏆 ПОВЫШЕНИЕ ЛИГИ! 🏆',
      'promoted_to': 'Поздравляем! Вы перешли в:',
      'promotion_note': 'Доход золота увеличен в 10 раз! Сложность сброшена.',
      'season_champion_title': '🏆 ЧЕМПИОН СЕЗОНА!',
      'season_ended_title': '🏁 Конец сезона',
      'new_season_btn': 'Начать новый сезон!',
      'your_points': 'Ваши очки:',
      'current_class': 'Текущий класс:',
      'class_promoted_note': '🎉 Вы финишировали 1-м! Класс повышен!',
      'sponsor_title': '🎌 Награда спонсора!',
      'sponsor_msg': 'Вы нажали на флаг спонсора!\nПродолжайте, чтобы получить золото.',
      'play_earn_btn': 'Смотреть и заработать',
      'sponsor_claimed': '🎌 Золото спонсора получено!',
      'welcome_back_title': '🐎 С возвращением!',
      'offline_earned_label': 'Стойло заработало в ваше отсутствие:',
      'offline_cap_note': 'Расчет за макс. 2 часа офлайна.',
      'collect_btn': 'Забрать',
      'double_ad_btn': 'Смотреть рекламу для 2X',
      'doubled_msg': '⚡ Ваш доход удвоен!',
      'insta_win_title': 'Билет мгновенной победы',
      'insta_win_desc': 'Мгновенно гарантируйте 1-е место!',
      'insta_win_success': '⚡ Мгновенная победа! 1-е место!',
      'gold_diamond_trade': 'Золото → Алмазы',
      'trade_btn': 'Обменять',
      'commentary_ready': '🏁 Ипподром готов! Гонка скоро начнется...',
      'commentary_gates_open': '🏁 Ворота открыты! Гонка началась!',
      'commentary_leading': '⚡ ВЫ ЛИДИРУЕТЕ! Так держать!',
      'commentary_rival_leads': 'вырывается вперед!',
      'commentary_finished_1st': '🏆 ВЫ ПОБЕДИЛИ! Финишировали 1-м!',
      'commentary_finished_top': 'финиш! Отличная работа!',
      'commentary_finished_low': 'финиш. Тренируйтесь усерднее!',
      'settings_title': 'Настройки',
      'settings_lang_label': 'Язык:',
      'settings_close': 'Закрыть',
      'settings_sound': 'Звуковые эффекты:',
      'settings_music': 'Музыка:',
      'settings_vibrate': 'Вибрация:',
      'settings_on': 'Вкл.',
      'settings_off': 'Выкл.',
      'promote_btn': 'Повысить',
      'restart_free_btn': 'Сбросить сезон (Бесплатно)',
      'promote_desc': 'Перейти в следующий класс / лигу.',
      'restart_desc': 'Начать сезон заново без повышения.',
      'col_rank': 'Место',
      'col_jockey': 'Жокей',
      'col_horse': 'Лошадь',
      'col_points': 'Очки',
      'ad_playing': 'Воспроизведение рекламы... Осталось:',
      'ad_completed': 'Реклама завершена!',
      'season_end_gold_cost': 'Плата:',
      'not_enough_gold_promote': 'Недостаточно золота для перехода!',
      // Upgrade Names and Descriptions
      'stat_speed_name': 'Скорость',
      'stat_speed_desc': 'Максимальная скорость',
      'stat_acceleration_name': 'Ускорение',
      'stat_acceleration_desc': 'Стартовый рывок',
      'stat_stamina_name': 'Выносливость',
      'stat_stamina_desc': 'Длинная дистанция',
      'stat_focus_name': 'Фокус',
      'stat_focus_desc': 'Сыгранность с жокеем',
      'stat_temper_name': 'Спокойствие',
      'stat_temper_desc': 'Под давлением',
      'stat_cornering_name': 'Повороты',
      'stat_cornering_desc': 'Контроль в поворотах',
      'skill_tactics_name': 'Тактика',
      'skill_tactics_desc': 'Стратегические решения',
      'skill_pacing_name': 'Темп',
      'skill_pacing_desc': 'Управление скоростью',
      'skill_reflexes_name': 'Reflexes',
      'skill_reflexes_desc': 'Instant reactions',
      'building_training_track_name': 'Парковка',
      'building_training_track_desc': 'Парковочная зона для посетителей',
      'building_medical_center_name': 'Тренировочный трек',
      'building_medical_center_desc': 'Непрерывные тренировочные круги',
      'building_feed_storage_name': 'Медицинский центр',
      'building_feed_storage_desc': 'Реабилитация и терапия',
      'building_research_lab_name': 'Денник',
      'building_research_lab_desc': 'Укрытие для лошадей',
      'building_luxury_stable_name': 'Люкс стойло',
      'building_luxury_stable_desc': 'Премиум условия проживания',
      'promotion_success': '🏆 Успешно повышено!',
      'chest_error_gold': 'Недостаточно золота или сундук закрыт!',
      'chest_error_diamond': 'Недостаточно алмазов или сундук закрыт!',
      'merge_error': 'Требуется 5 дубликатов карт для слияния!',
    },
  };

  static String get(String locale, String key) {
    final result = _strings[locale]?[key];
    if (result != null) { return result; }
    final fallback = _strings['tr']?[key];
    if (fallback != null) { return fallback; }
    debugPrint('⚠️ Missing string key: $key for locale: $locale');
    return key;
  }
}
